#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from __future__ import print_function
from __future__ import unicode_literals

# We enable monkey patching to make many libraries gevent-friendly
# (for instance, urllib3, used by requests)
import gevent.monkey
gevent.monkey.patch_all()

import logging
import sys

from cms import ConfigError, default_argument_parser
from cms.db import test_db_connection
from cms.server.integration import IntegrationWebServer


logger = logging.getLogger(__name__)


def main():
    """Parse arguments and launch service.

    """
    test_db_connection()
    success = default_argument_parser("Integration web server for CMS.",
                                      IntegrationWebServer).run()
    return 0 if success is True else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except ConfigError as error:
        logger.critical(error.message)
        sys.exit(1)
